import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import { ThemeProvider } from "next-themes";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/component/App-sidebar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
          storageKey="theme"
        >
          <SidebarProvider>
            <Header />
            <div className="flex max-w-full">


              <AppSidebar />

              <div className="w-screen mt-[100px] min-h-[calc(100vh-120px)]" >
                {children}</div>

            </div>
          </SidebarProvider>


          {/* <SidebarProvider>
            <AppSidebar />
            <main>
              <SidebarTrigger />
            </main>
          </SidebarProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
